# reenable and fix warnings 1 by 1 later
disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name
  - function_parameter_count
  - unused_optional_binding
  - todo
  - redundant_discardable_let
  - empty_parameters
  - trailing_newline
  - protocol_property_accessors_order
  - closure_parameter_position
  - mark
  - vertical_whitespace
  - for_where
  - colon
  - weak_delegate
  - redundant_optional_initialization

excluded:
  - Pods

force_cast: error
force_try: error

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 2 # only warning
  max_length:
    warning: 40
    error: 50

function_parameter_count:
  warning: 4
  error: 6

cyclomatic_complexity:
  warning: 6
  error: 8

variable_name:
  min_length: 2
