language: objective-c

branches:
    only:
        - develop

xcode_workspace: Vyrl.xcworkspace
xcode_scheme: Vyrl
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

before_install:
    - echo y | fastlane snapshot reset_simulators
    # - fastlane enable_crash_reporting
    # - sudo gem update fastlane
    # - sudo gem install cocoapods

install:
    # - pod install
    # - sudo gem update fastlane

before_script:
    # - fastlane/./unlock_keychain.sh

script:
    - xcodebuild -workspace Vyrl.xcworkspace -scheme Vyrl -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.2' test
    # - xcodebuild clean build test -project Vyrl.xcworkspace -scheme Vyrl
    # - fastlane inhouse


# after_success:


# after_failure:


# after_script:
